### ISSUE TITLE
Adapt SHAWI data management workflows to include audio files

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/shawi-data#10]
We have wav files and we have timestamps in TEI XML.

We need a way to cut the wav files and also probably to export them as mp4.

One way to do this is to transform the TEI files to [audacity 2](https://www.fosshub.com/Audacity-old.html?dwl=audacity-win-2.4.2.exe) project files which also happen to be XML files.

**Comment by simar0at** [comment]
The aup xml file is very much hard wired to the _data folder next to it.  
The wav file needs to be imported to the audiacity 2 project first and then the "text" tracks with the timestamp info can be added.

**Comment by dasch124** [comment]
IMO we should go for the CSV/TSV format which seems less effort to create.

**Comment by dasch124** [comment]
The TSV format is described here: https://manual.audacityteam.org/man/importing_and_exporting_labels.html

This should be generated by taking all `<u>` elements and including the calculate the time from the `<when>` elements in the  `<timeline>` in the TEI documents in 010_manannot:

```xml 
  <timeline unit="ms">
         <when xml:id="T0"/>
         …
               <when interval="197124" since="#T0" xml:id="T19"/>
                <when interval="197256" since="#T0" xml:id="T20"/>
          …
      </timeline>
     …
    <annotationBlock>
               <u xml:lang="ar-acm-x-shawi-vicav" xml:id="URFA-034_a20" who="#default" end="#T20" start="#T0">
                  … 
              </u>
    <annotationBlock>    
```

Instead of having the speaker name as the label, we should have the utterance's xml:id, so the exported audio snippet can be id.

**Comment by dasch124** [comment]
for some reason, the xml:id is missing from the @url attribute on <media>, e.g. https://github.com/acdh-oeaw/shawi-data/blob/main/010_manannot/Urfa-097_Three_Daughters-Harran-2010.xml#L210

**Comment by rausch-supola** [comment]
As I said, I only inserted the two lines
<media mimeType="audio/mp3" url="publicAssets:{textID}/{utterance-id}.mp3"></media>
<media mimeType="audio/wav" url="arche:{textID}/{utterance-id}.wav"></media>

I guess the linking to the data is missing

**Comment by rausch-supola** [comment]
As I said, I only inserted the two lines
"<media mimeType="audio/mp3" url="publicAssets:{textID}/{utterance-id}.mp3"></media>
<media mimeType="audio/wav" url="arche:{textID}/{utterance-id}.wav"></media>"

I guess the linking to the data is missing

**Comment by rausch-supola** [comment]
As I said, I only inserted the two lines with the <media> attribute. I guess the linking to the data is missing

**Comment by rausch-supola** [comment]
As I said, I only inserted the two lines with the attribute media. I guess the linking to the data is missing

**Comment by rausch-supola** [comment]
As I said I only inserted the two lines with the media tag. I guess the linking to some data is missing

**Comment by rausch-supola** [comment]
this issue can be closed I guess @dasch124 ?
