### ISSUE TITLE
transform ellipsis to TEI

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/shawi-data#14]
* unfinished words: three dots attached to word without space: TODO decide how to represent in TEI
* omissions in the transcription: three dots in square brackets with space before: `<gap/>`

**Comment by dasch124** [comment]
2024-02-01: 

We want to encode unfinished words with `<w type="truncated">`, removing the ellipsis sign.

**Comment by dasch124** [comment]
Cf. https://github.com/acdh-oeaw/shawi-data/blob/main/080_scripts_generic/080_01_ELAN2TEI/truncate_and_elipsis.xsl

**Comment by dasch124** [comment]
Replace 

```xml
<pc join="right" xml:id="xTok_000211">[</pc>
<pc xml:id="xTok_000212">…</pc>
<pc xml:id="xTok_000213">]</pc>
```

with `<gap rend="elipsisWithinSquareBrackets"/>`

**Comment by rausch-supola** [comment]
done with https://github.com/acdh-oeaw/shawi-data/commit/54c561eed7654f769eac1557a356fb1aed64f46c and https://github.com/acdh-oeaw/shawi-data/commit/64d1d886be38dd54806f9d3aaa4ee7438fd72dac
