### ISSUE TITLE
Define rules for SHAWI dictionary

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/shawi-data#22]
We probably need to create a SHAWI-specific ODD for the dictionary based on the [ACDH-CH Generic Dict Schema](https://github.com/acdh-oeaw/generic-dict-schema/) (which itself is based on TEI Lex0)

* We need to incorporate geographic distribution of word forms / variants. Require `<usg type="geo">` inside `<form type="variant">` ? 

other rules specific to SHAWI ?

**Comment by rausch-supola** [comment]
These are some points we should discuss:

include sourceDesc
role attribute is not allowed in language? don't understand why it is an error, should be allowed according to tei lex0
<w pos="pronoun"/> --> only twice, remove?
gramGrp as child of cit --> occurs only once
gram should be child of cit? in tei lex0: GramGrp --> change to <cit>..<gramGrp><gram></gram></gramGrp></cit>?
<gram type="constraints">? change to constraint?
gram type morphPattern should be included or rather replace it with morphPatternSg/morphPatternPl?
<gram type="rection" (once)? should be included?
remove "ä", "#l" and " g"
form: type attribute is required and cannot be optional the same time?
cit type="translation" or "translationEquivalent" --> seems a bit confusing, children are quote, bibl, cit, usg, form, fs, ..
form variant as child of form variant?
form lemma is child of form lemma?
form type variant is child of entry, not of form type lemma

**Comment by rausch-supola** [comment]
We discussed the last time: 

1) cit type translation
is followed by a quote (same says the description of the rule "a translation may only contain the translated text in a quote element"). However, there are quite a few cit > bibl > form, cit > cit and one cit > fs. At least the last one looks like a mistake. What is with the other ones? 

2) cit type translationEquivalent
occurs after a sense element

But the same is right for the cit type translation? 
```
					<sense xml:id="DShaAr.s_hadanne_000_0">
						<cit type="translation" xml:lang="en">
							<quote>these</quote>
						</cit>
						<cit type="translation" xml:lang="de">
							<quote>diese</quote>
						</cit>
						<cit type="translation" xml:lang="tr">
							<quote>bunlar</quote>
						</cit>
					</sense>
```

There should be a rule defining that a translationEquivalent follows after sense. There already is a rule like this but for cit type translation:
                   
```
<s:rule context="tei:entry//tei:cit[@type = 'translation']">
       <s:assert test="parent::tei:sense">a translation in a headword or MWU entry must be a direct child of a sense element</s:assert>
</s:rule>
```
Should this rule be kept as well?

Somethong wrong happened here I guess? -->
```
					<sense xml:id="DShaAr.s_gibbal_000_0">
						<cit type="translationEquivalent" xml:lang="en">
							<quote>to turn into the direction of Mecca</quote>
						</cit>
						<cit type="translation" xml:lang="de">
							<quote>in Richtung Mekka drehen</quote>
						</cit>
						<cit type="translation" xml:lang="tr">
							<quote>Mekke ile yüzleşmek</quote>
						</cit>
					</sense>
```

A cit type translationEquivalent is not followed by a quote, right? But by form without type, bibl, and usg type hint

**Comment by rausch-supola** [comment]
I guess this issue can be closed/is worked on in other issues? @dasch124
