### ISSUE TITLE
Convert Shawi-Dict to Lex-0

### ISSUE THREAD

**Issue by charlymo** [acdh-oeaw/shawi-data#3]
1. usg[@type="hint"] ==> gloss
2. transfer morphPatterns into form's
3. deal with bibl (cf. running minutes)

**Comment by VeronikaEngler** [comment]
@dasch124 does this concern only the <bibl>-elements in sense/cit/bibl or generally all <bibl>-elements including e.g. entry/form/bibl:
<entry xmlns="http://www.tei-c.org/ns/1.0" xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.arbaca_000">
		<form type="lemma">
			<usg type="geographic">
				<placeName>Harran-Urfa</placeName>
			</usg>
			<usg type="geographic">
				<placeName>Bekaa</placeName>
				<name type="tribe">Idin|Abu Id</name>
			</usg>
			**<bibl corresp="zot:Younes2021">p.44</bibl>**
			<orth>arbaʕa</orth>
			<note type="workflow">addedByCharly</note>
		</form>
		
		or entry/form/form/bibl:
