### ISSUE TITLE
dict: strange gram type

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#34]
in line 159306 is `<gram type="morphPatternḏl" xml:lang="ar-acm-x-shawi-vicav">1a2ā2ī3</gram>`

**Comment by charlymo** [comment]
Das war eom morphPatternPl. bei der Tastaturbelegung für das Wörterbuch liegt das Zeichen ḏ auf dem P.

**Comment by rausch-supola** [comment]
fixed
