### ISSUE TITLE
dict: element w

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#37]
There are still occurrences of the w element that are not allowed:

```
<orth>ḥakk ḥāl-<w pos="pronoun"/>
<orth>yḥukk ḥāl-<w pos="pronoun"/>
```

**Comment by charlymo** [comment]
should be replaced by
  <orth>ḥakk ḥāl-</orth>​
      <gramGrp><gram type="followedBy">persSuffix</gram></gramGrp>​

**Comment by rausch-supola** [comment]
seems solved
