### ISSUE TITLE
dict: ref not allowed

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#39]
there is a ref type bibl in usg type geographic which throws an error, e.g.

`            <entry xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.staahal_000">
               <form source="#d1e285152" type="lemma">
                  <usg type="geographic">
                     <placeName>Jbur</placeName>
                     <name type="tribe">Jbur</name>
                     <placeName>Tayy</placeName>
                     <name type="tribe">Tayy</name>
                     <ref type="bibl">Bettini 2006:359</ref>`

6 times

**Comment by charlymo** [comment]
Should be manually changed to new listBibl

**Comment by rausch-supola** [comment]
maybe the ref type bibl line should manually be removed? it does not throw an error any more but is still there, and the bibl information is in listBibl below

**Comment by kisram** [comment]
When we talked about this in the JF last Tuesday, we ended up [changing the content model of usg](https://github.com/acdh-oeaw/generic-dict-schema/commit/0907f7607b86c1538d5a1cec1202664e6d2b541e), so the errors disappeared. We should talk about whether it should stay this way or if the refs should be changed to listBibl (and the content model of usg adjusted again) like @charlymo suggested here

**Comment by rausch-supola** [comment]
the six lines with ref type bibl should be manually removed
generic dict odd should be adapted

**Comment by rausch-supola** [comment]
xml:id="DShaAr.staahal_000"
xml:id="DShaAr.bidd_000" (twice)
xml:id="DShaAr.birza_001"
xml:id="DShaAr.yibra_lig_gimal_000"
xml:id="DShaAr.yibra_lig_gimal_000"

**Comment by VeronikaEngler** [comment]
fixed

**Comment by rausch-supola** [comment]
still one left? xml:id="DShaAr.bidd_000"

**Comment by VeronikaEngler** [comment]
fixed bidd-
