### ISSUE TITLE
Translate hasDash to actual dashes for Noske vertical

### ISSUE THREAD

**Issue by charlymo** [acdh-oeaw/shawi-data#4]

**Comment by simar0at** [comment]
Dashes are visible now and have to be considered in searches 1574b8dd73e3bbc7666117bc555ad8fe73dd11c5
* [simple al](https://shawi-noske.acdh-dev.oeaw.ac.at/crystal/#concordance?corpname=shawi&tab=basic&keyword=al&attrs=word&viewmode=kwic&attr_allpos=all&refs_up=0&shorten_refs=1&glue=1&gdexcnt=300&show_gdex_scores=0&itemsPerPage=20&structs=&refs=%3Ddoc.id%2C%3Du.id&showresults=1&showTBL=0&tbl_template=&gdexconf=&f_tab=basic&f_showrelfrq=1&f_showperc=0&f_showreldens=0&f_showreltt=0&c_customrange=0&operations=%5B%7B%22name%22%3A%22iquery%22%2C%22arg%22%3A%22al%22%2C%22query%22%3A%7B%22queryselector%22%3A%22iqueryrow%22%2C%22iquery%22%3A%22al%22%7D%2C%22id%22%3A939%7D%5D)
* [CQL "al""-"?[word!="-"]](https://shawi-noske.acdh-dev.oeaw.ac.at/crystal/#concordance?corpname=shawi&tab=advanced&queryselector=cql&keyword=al%20-%3F%20*&attrs=word&viewmode=kwic&attr_allpos=all&refs_up=0&shorten_refs=1&glue=1&gdexcnt=300&show_gdex_scores=0&page=12&itemsPerPage=20&structs=&refs=%3Ddoc.id%2C%3Du.id&default_attr=word&cql=%22al%22%22-%22%3F%5Bword!%3D%22-%22%5D&showresults=1&showTBL=0&tbl_template=&gdexconf=&f_tab=basic&f_showrelfrq=1&f_showperc=0&f_showreldens=0&f_showreltt=0&c_customrange=0&operations=%5B%7B%22name%22%3A%22cql%22%2C%22arg%22%3A%22%5C%22al%5C%22%5C%22-%5C%22%3F%5Bword!%3D%5C%22-%5C%22%5D%22%2C%22query%22%3A%7B%22queryselector%22%3A%22cqlrow%22%2C%22cql%22%3A%22%5C%22al%5C%22%5C%22-%5C%22%3F%5Bword!%3D%5C%22-%5C%22%5D%22%2C%22default_attr%22%3A%22word%22%7D%2C%22id%22%3A8785%7D%5D)
