### ISSUE TITLE
dict: listBibl requires type 

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#40]
element "listBibl" missing required attribute "type" - we discussed that we have to insert a type, preferably "literature"

**Comment by charlymo** [comment]
rather "sources" than "literature"

**Comment by rausch-supola** [comment]
fixed

**Comment by VeronikaEngler** [comment]
We actually want literature, not source (in accord with lex-0)

**Comment by VeronikaEngler** [comment]
fixed
