### ISSUE TITLE
dict: cit type translationEquivalent

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#44]
we defined in the odd that cit type translationEquivalent has to be a child of a sense element. There are some exceptions: it occurs as a child of form type inflected, as a child of an entry or as a child of a cit type example (altogether 13 times)

**Comment by rausch-supola** [comment]
xml:id="DShaAr.saar_000"
xml:id="DShaAr.saar_000"
xml:id="DShaAr.kook_000"
xml:id="DShaAr.al_dash_habaayib_tikaawanan_001"
xml:id="DShaAr.id_368"
xml:id="DShaAr.tayyah_beet_ummu_000"
xml:id="DShaAr.wahdin_garr_caleecjin__000"
xml:id="DShaAr.haddaraw_l_faras_000"
xml:id="DShaAr.maa_fii_cjaara_000"
xml:id="DShaAr.hattatha_b_ladd__001"
xml:id="DShaAr.hattatha_b_ladd__001"
xml:id="DShaAr.shahar_yhill_w__000"
xml:id="DShaAr.walla_alla_ywull__000"

**Comment by VeronikaEngler** [comment]
fixed
