### ISSUE TITLE
dict: form type variant

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#46]
.. is a child of a form type variant 2 times (29785, 29809) and child of an entry 2 times (86918, 140417), but has to be child of form type lemma, multiWordUnit or inflected

**Comment by rausch-supola** [comment]
xml:id="DShaAr.faqiir_00000" (twice)
xml:id="DShaAr.na_001"
xml:id="DShaAr.w_000"

**Comment by VeronikaEngler** [comment]
Fixed xml:id="DShaAr.na_001" and xml:id="DShaAr.w_000". 
In xml:id="DShaAr.faqiir_00000" it might make sense contentwise to keep the 'fəgīr' as a variant of the variant 'fəqīr', what do you think @charlymo and @Prochas8?

**Comment by VeronikaEngler** [comment]
fixed
