### ISSUE TITLE
dict: form type lemma

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#48]
.. has to be direct child of entry but here it is child of another form type lemma (`<entry xmlns="http://www.tei-c.org/ns/1.0" xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.gcade_00000">`)

**Comment by dasch124** [comment]
should be form type="variant"

**Comment by VeronikaEngler** [comment]
Fixed
