### ISSUE TITLE
dict: gram type morphPattern 

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#49]
.. has to be grandchild of a form with a type attribute but for 5 times it's grandchild of an entry 
(the parent gramGrp is fine in all occurrences)

**Comment by charlymo** [comment]
It would be helpful to have some cases identified by entry/@xml:id to quickly check it in these issues.

**Comment by rausch-supola** [comment]
the gram is always in gramGrp, so that's ok. These are the entries:

<entry xmlns="http://www.tei-c.org/ns/1.0" xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.misraan_00000">
<entry xmlns="http://www.tei-c.org/ns/1.0" xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.zgayyir_00000">
<entry xmlns="http://www.tei-c.org/ns/1.0" xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.zgayyruun_00000">
<entry xmlns="http://www.tei-c.org/ns/1.0" xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.cagrab_00000">
<entry xmlns="http://www.tei-c.org/ns/1.0" xml:lang="ar-acm-x-shawi-vicav" xml:id="DShaAr.catshaan_00000">

**Comment by rausch-supola** [comment]
editing my comment: 

> the gram is always in gramGrp

the gram type morphPattern is always in a gramGrp. The other grams not being in a gramGrp are handled in issue #58

**Comment by dasch124** [comment]
`<gramGrp>` with `morphPattern` should be moved inside form type="lemma"
