### ISSUE TITLE
dict: gramGrp should not be empty

### ISSUE THREAD

**Issue by charlymo** [acdh-oeaw/shawi-data#51]
minOccurs="1"

**Comment by rausch-supola** [comment]
inserted specification in odd and uploaded it, there are 11 empty gramGrps

**Comment by dasch124** [comment]
please remove

**Comment by rausch-supola** [comment]
xml:id="DShaAr.da_000"
xml:id="DShaAr.damce_00000"
xml:id="DShaAr.di_000"
xml:id="DShaAr.gaab_00000"
xml:id="DShaAr.i_000"
xml:id="DShaAr.saag_000"
xml:id="DShaAr.sallam_00000"
xml:id="DShaAr.tabb_00000"
xml:id="DShaAr.xallas_00000"
xml:id="DShaAr.gaar_000"
xml:id="DShaAr.gabbat_000"

**Comment by VeronikaEngler** [comment]
fixed
