### ISSUE TITLE
typing of multi-word units

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/shawi-data#53]
currently, MWEs are indicated by `<gram pos="multiWordUnit">` 
This `gram` should be removed and the @type on the headword (now reading "lemma") be replaced by "compound"

**Comment by VeronikaEngler** [comment]
Transformation is done, but @type="compound" needs to be added to the schema.

**Comment by VeronikaEngler** [comment]
Decision in Jour Fixe:  we go with <form type="lemma" subtype="compound">

**Comment by kisram** [comment]
Done. It's included in the generic dict ODD
