### ISSUE TITLE
dict: text not allowed again

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#57]
occurs once, line 248325

`		<gramGrp>
			<gram type="pos">adjective</gram>
                  s
                  <gram type="synRoot" xml:lang="ar-acm-x-shawi-vicav">xṭr</gram>
			<gram type="diaRoot" xml:lang="ar">xṭr</gram>
		</gramGrp>`

**Comment by rausch-supola** [comment]
xml:id="DShaAr.xatiir_000"

**Comment by VeronikaEngler** [comment]
was already fixed
