### ISSUE TITLE
dict: gram not in gramGrp

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#58]
there are 25 gram elements that don't occur in a gramGrp, concerned are following entries:

xml:id="DShaAr.mhabuul_00000"
xml:id="DShaAr.secaafiig_000"
xml:id="DShaAr.mud_acniin_000"
xml:id="DShaAr.caslagiyya_000"
xml:id="DShaAr.hukshaw_l_xeel_000"
xml:id="DShaAr.laa_fcal_adfinha__000"
xml:id="DShaAr.wal_yibtah_rifiigu__000"
xml:id="DShaAr.ridit_hidit_raadaw__000"
xml:id="DShaAr.haafan_az_zruub_000"
xml:id="DShaAr.laa_hool_w__000"
xml:id="DShaAr.ta_nriid_nxatm__000"
xml:id="DShaAr.lummin_ma_nxumm_000"
xml:id="DShaAr.xoosh_bshaara_000"
xml:id="DShaAr.xoosh_iswa_000"
xml:id="DShaAr.darrbu_cal_mara_000"
xml:id="DShaAr.adca_galubha_daciif_000"
xml:id="DShaAr.yidcii_shnoon_habb_000"

**Comment by dasch124** [comment]
Should be fixed manually

**Comment by rausch-supola** [comment]
seems fixed
