### ISSUE TITLE
@xml:lang on utterances is wrong

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/shawi-data#6]
`@xml:lang` on `<u>` should read "ar-acm-x-shawi-vicav" (currently it reads "x-vicav-shawi")

needs to be updated both in the XSLT in the resulting TEI documents in `010_manannot`

https://github.com/acdh-oeaw/shawi-data/blob/5056d605f1304203b1c85ceef08aa6060b2a7dec/082_scripts_xsl/mergeHeaderAndTranscription.xsl#L69

**Comment by likeanga** [comment]
I ran the pipeline and "ar-acm-x-shawi-vicav" doesn't occur anymore.

**Comment by dasch124** [comment]
sorry, the original description was wrong :roll_eyes: it's actually the other way round: the attribute should read "ar-acm-x-shawi-vicav" (currently it reads "x-vicav-shawi") [updated the original wording]
