### ISSUE TITLE
If form[@type="lemma"]/orth has a blank, then it should have subtype="compound"

### ISSUE THREAD

**Issue by charlymo** [acdh-oeaw/shawi-data#72]
e.g. DShaAr.ciid_ad_d__000; Schematron?

**Comment by rausch-supola** [comment]
I add the rule to the odd (https://github.com/acdh-oeaw/shawi-data/commit/5f6e038a0d8b71b9b141725461eed1355246b1d4) 

It occurs around 164 times

**Comment by VeronikaEngler** [comment]
correct errors

**Comment by rausch-supola** [comment]
often there are spaces at the end of the string, e.g. <orth>ǧidriyye </orth> in the item xml:id="DShaAr.gidriyye_00000"
Should the space be removed in the dictionary or should the compound rule ignore these cases?

**Comment by VeronikaEngler** [comment]
fixed
