### ISSUE TITLE
create sensible document titles from filenames

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/shawi-data#74]
Currently the `<title>` of each document is only its ID - we would like to create a more readable title from the filename, e.g. "Smoking Harran" for [Urfa-029_Smoking-Harran-2010.xml](https://github.com/acdh-oeaw/shawi-data/blob/main/010_manannot/Urfa-029_Smoking-Harran-2010.xml)` 

We need to run this on the existing documents in 010_manannot and integrate the script into the jupyter notebook as well, so the title is already correct in the newly created documents.

**Comment by rausch-supola** [comment]
finished
