### ISSUE TITLE
dict: gram[type="precededBy" attribute value not allowed

### ISSUE THREAD

**Issue by VeronikaEngler** [acdh-oeaw/shawi-data#76]
Error message:
 cvc-enumeration-valid: Wert 'precededBy' ist nicht Facet-gültig in Bezug auf Enumeration '[arguments, aspect, constraint, degree, diaRoot, diaRootNew, frequency, followedBy, gender, government, inflectionType, morphPattern, nominalState, number, person, pos, root, subc, synRoot, usg]'. Er muss ein Wert aus der Enumeration sein.

This error occurs in DShaAr.nafis_0001

**Comment by rausch-supola** [comment]
I already fixed it in the generic dict: https://github.com/acdh-oeaw/generic-dict-schema/commit/717154a8ebd2f3b7b35efbe60ddeccac35e567d9
