### ISSUE TITLE
dict: cit type translation child

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/shawi-data#80]
"tei:cit/@type = 'translation' may only contain a tei:quote element" but here it is form orth:

xml:id="DShaAr.al_dash_habaayib_tikaawanan_001"
xml:id="DShaAr.id_368"
xml:id="DShaAr.tayyah_beet_ummu_000"
xml:id="DShaAr.wahdin_garr_caleecjin__000"
xml:id="DShaAr.haddaraw_l_faras_000"
xml:id="DShaAr.maa_fii_cjaara_000"
xml:id="DShaAr.hattatha_b_ladd__001"
xml:id="DShaAr.hattatha_b_ladd__001"
xml:id="DShaAr.shahar_yhill_w__000"
xml:id="DShaAr.walla_alla_ywull__000"

**Comment by VeronikaEngler** [comment]
Replace with quote

**Comment by VeronikaEngler** [comment]
fixed
