### ISSUE TITLE
add revision desc + @status to corpus files in manannot

### ISSUE THREAD

**Issue by VeronikaEngler** [acdh-oeaw/shawi-data#90]
the corpus files in 010_manannot should have a revisionDesc element and a @status to indicate whether the manual annotation is done

status could be:

_generated_ (status automatically generated by elan2tei conversion)
_draft_ (when changes are made in file in 010_manannot folder manually)
_done_ (from here on validation with odd can start)
_checked_
_published_ (when checked and validated)

this change has to be made 

- [x] for already existing files as well as 

- [x] for future files

- [x] Add revisionDesc and statuses to ODD/schema too

**Comment by rausch-supola** [comment]
status could be:

draft
done (from here on validation with odd can start)
checked
published (when checked and validated)

**Comment by rausch-supola** [comment]
I made the changes in the data. Somehow, when I ran the script on the already existing files in manannot, a lot of spaces have been removed. Maybe somebody could check if everything important remained as it should be? 

still to do: odd

**Comment by rausch-supola** [comment]
Do we want to have detailed records on when and who changed the file? Since the revisionDesc must have a change element, we have to add one like `<change when="1991-11-11" who="#LB"> deleted chapter 10 </change>`, or `<change/>` at least.

**Comment by rausch-supola** [comment]
completed
